services:
  - type: web
    name: syntaxquiz-api
    runtime: Docker
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.10